Modelagem do banco de dados
utfpr-gp/auto-repair-shop pull request #2
Opened 2019-06-12 23:18 UTC by BrunaBelo

2019-06-13 21:50 UTC, ronifabio requested changes

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Adress.java
> +@Data
@Data já contém @Getter e @Setter

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Adress.java
> +@Table(name="adresses")
addresses com duas letras d

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Adress.java
> +	private Long idAdress;
Renomear somente para id

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Adress.java
> +	private int number;
Nem sempre o endereço tem números, às vezes pode ser S/N (Sem número) ou conter letras, ex: casa 10A. Mudar para String.

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Adress.java
> +	public Adress(Long idAdress, String street, String city, String state, String cep, int number) {
Como o id tem @GeneratedValue(strategy = GenerationType.IDENTITY), o id é gerado automaticamente pelo banco. Não se deve passar pelo construtor.

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Client.java
> +	public Client(Long idClient, Adress idAdress, Credentials idCredentials, Date dataBirth, String name, String telephone) {
Id é gerado pelo banco, não passar no construtor

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Client.java
> +	private Adress idAdress;
Address

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Credentials.java
> +	public Credentials(Long idCredentials, String email, String password) {
Id gerado pelo banco

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Credentials.java
> +	private Long idCredentials;
Renomear para id

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Client.java
> +	private Long idClient;
Renomear para id

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Employees.java
> +	private Long idEmployee;
Renomear para id

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Employees.java
> +	private Credentials idCredentials;
Renomear para credential

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Employees.java
> +	private Long idWorkshop;
Não entendi o que representa. Se for oficina, deve ser representado por um relacionamento @ManyToOne, não como Long.

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Employees.java
> +	private Adress idAdress;
Ao invés de idAddress, usar somente address

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Employees.java
> +	public Employees(Long idEmployee, Credentials idCredentials, Long idWorkshop, Adress idAdress, String name,
Remover o idEmployee do construtor

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/MechanicalWorkshops.java
> +	private Long idworkshop;
Só id

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/MechanicalWorkshops.java
> +	private Adress idAdress;
address

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Client.java
> +	private Date dataBirth;
Renomear para dateBirth

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Service.java
> +	private Long idService;
id

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Service.java
> +	private Client idClient;
Renomear para clientId

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Service.java
> +	private Employees idFuncMechanical;
Renomear para employeeId

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/MechanicalWorkshops.java
> +	public MechanicalWorkshops(Long idworkshop, Adress idAdress, String name, String cnpj, String telephone,
Renomear para AutoRepairShop

2019-06-13 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Vehicle.java
> +	private Client idClient;
Renomear para client apenas

2019-06-18 00:27 UTC, agsgoudinho commented on src/main/java/br/edu/utfpr/autorepairshop/model/Client.java
> +@Setter
Não precisa do @Getter e @Setter quando você usa @Data

2019-06-18 00:31 UTC, agsgoudinho commented on src/main/java/br/edu/utfpr/autorepairshop/model/Client.java
> +@Table(name="client")
mudar nome da tabela para o plural

2019-06-18 00:35 UTC, agsgoudinho commented on src/main/java/br/edu/utfpr/autorepairshop/model/Client.java
> +	public Client(Long id) {
Tirar o parâmetro não utilizado

2019-06-18 00:58 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/Adress.java
> +@Data
sdfsdf

2019-06-18 15:56 UTC, ronifabio approved these changes

2019-06-19 21:47 UTC, merged