Feature/cadastro de veiculos
utfpr-gp/auto-repair-shop pull request #4
Opened 2019-06-23 20:43 UTC by Matheus-Mazepa

- Criação de cadastro e listagem de veículos;
- Correção menu;

2019-06-25 00:09 UTC, ronifabio requested changes
Precisa resolver os comentários

2019-06-25 00:09 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/controller/VehicleController.java
> +        VehicleDTO studentDTO = vehicleMapper.toResponseDto(optionalVehicle.get());
studentDTO

2019-06-25 00:09 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/dto/VehicleDTO.java
> +    @NotEmpty(message = "Placa é obrigatório.")
Pattern/REGEX de placa

2019-06-25 00:09 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/dto/VehicleDTO.java
> +    private Client client;
Referenciar ClientDTO

2019-06-25 00:09 UTC, BrunaBelo requested changes

2019-06-25 00:09 UTC, BrunaBelo commented on src/main/java/br/edu/utfpr/autorepairshop/controller/VehicleController.java
> +    @GetMapping("/criar")
Alterar o nome da rota para /novo

2019-06-25 00:09 UTC, BrunaBelo commented on src/main/java/br/edu/utfpr/autorepairshop/controller/VehicleController.java
> +        //Apenas durante teste
Remover o teste de cadastro do cliente

2019-06-26 22:57 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/service/service-client.jsp
> +<t:template title="Estrato de atendimentos">
Extrato

2019-06-26 22:57 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/vehicle/form.jsp
> +                                <div class="title-form">Cadastro de veiculo</div>
veículo com acento

2019-06-26 22:57 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/vehicle/form.jsp
> +                                            <label>Dono</label>
Proprietário

2019-06-26 22:58 UTC, merged