Cadastro clientes
utfpr-gp/auto-repair-shop pull request #5
Opened 2019-06-23 22:48 UTC by hythan

Telas de cadastra o cliente e seu carro.

2019-06-25 00:51 UTC, Lucassamuel97 commented on src/main/java/br/edu/utfpr/autorepairshop/controller/ClientController.java
> +        Client client = clientService.save(clientDTO);
A conversão de clienteDTO para client deve ser feita no controller, através de uma classe ClientMapper.

2019-06-25 01:00 UTC, Lucassamuel97 requested changes
Pull request devera ir para branch dev

2019-06-25 01:04 UTC, leivans requested changes
Mudar a branch base, de master para develop

2019-07-03 21:59 UTC, Matheus-Mazepa approved these changes

2019-07-03 21:59 UTC, Matheus-Mazepa commented on src/main/resources/application.properties
> +# n�veis de log dispon�veis: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
Verificar encoding

2019-07-03 22:24 UTC, merged