Edit, List e Delete Client
utfpr-gp/auto-repair-shop pull request #9
Opened 2019-07-09 03:01 UTC by hythan

Feito o editar, listagem e delete do cliente.

2019-07-10 02:26 UTC, BrunaBelo requested changes

2019-07-10 02:26 UTC, BrunaBelo commented on src/main/java/br/edu/utfpr/autorepairshop/controller/ClientController.java
> +        System.out.println("ADWDKNAWKDNAWDKLNAWKLD"+ clientDataDTO.getBirthDate());
Remover linha de teste

2019-07-10 02:26 UTC, BrunaBelo commented on src/main/java/br/edu/utfpr/autorepairshop/controller/ClientController.java
> +        System.out.println("CHEGOUUUU AQUI!!" + client.getBirthDate());
remover linha de teste

2019-07-10 02:26 UTC, BrunaBelo commented on src/main/java/br/edu/utfpr/autorepairshop/controller/ClientController.java
>          clientService.save(client);
Um cliente pode adicionar um e-mail que ja existente no banco, isso pode dar algum conflito no login

2019-07-10 19:54 UTC, ronifabio requested changes

2019-07-10 19:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/controller/ClientController.java
>          Address address = addressMapper.toEntity(clientDataDTO);
A boa prática ser o argumento ser AddressDTO ao invés de clientDataDTO

2019-07-10 19:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/dto/ClientDataDTO.java
>      private String birthDate;
Como é String, usar Pattern para validar. O DateTimeFormat é usado para Date, mas não tem possibilidade de definir a mensagem de erro

2019-07-10 19:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/dto/ClientDataDTO.java
>      private String email;
Usar @Email para validar

2019-07-10 19:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/autorepairshop/model/dto/ClientDataDTO.java
>      private Address address;
Como é um objeto não primitivo e aninhado, não será validado pelo Bean Validation por dafaul. Colocar a anotação @Valid nele. Também, seria interessante se fosse AddressDTO.

2019-07-10 19:54 UTC, ronifabio commented on src/main/webapp/assets/res/js/index.js
> +        format: 'dd/mm/yyyy'
Usar o formato dd/MM/yyyy. Note que se usa MM maiúsculo para meses, os minúsculos referem-se a minutos.

2019-07-11 16:16 UTC, ronifabio approved these changes

2019-07-11 22:44 UTC, BrunaBelo approved these changes

2019-07-12 01:56 UTC, merged